version: '3.8'

services:
  python:
    build: .
    container_name: python-app
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      bash -c "
        pip install -r requirements.txt &&
        python operaciones_4_poc.py &&
        sleep infinity
      "
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./app/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data: